[package]
name = "wasmi-benchmarks"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
    "benches/res/rust/*"
]

[dependencies]
wasmi_old = { package = "wasmi", version = "0.31" }
wasmi_new = { package = "wasmi", version = "0.32.0-beta.15", features = ["no-hash-maps"] }
tinywasm = "0.6.0"
wasmer = { version = "4.2.8", default-features = false, features = ["engine", "compiler"] }
wasmer-compiler-singlepass = "4.2.8"
wasmer-compiler-cranelift = "4.2.8"
wasmtime = { version = "20.0", default-features = false, features = ["winch", "cranelift", "runtime"] }
criterion = "0.5"
wat = "1"

[dependencies.wasm3]
git = "https://github.com/robbepop/wasm3-rs.git"
branch = "rf-fix-wasm3-rs"
features = ["build-bindgen"]

[[bench]]
name = "criterion"
harness = false

[profile.bench]
# debug = true
lto = "fat"
codegen-units = 1

[profile.wasm]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
