name: Rust - Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Disable running jobs on earlier commits.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    install-dependencies:
      name: Install Dependencies
      runs-on: ubuntu-latest
      steps:
        - name: Install fontconfig and ninja
          # - libfontconfig1-dev: required for plotters
          # - ninja-build: required for Wasmer's WAMR backend
          run: |
            sudo apt-get update
            sudo apt-get install -y libfontconfig1-dev ninja-build

    check:
        name: Build
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
          - uses: dtolnay/rust-toolchain@stable
          - name: Set up Cargo cache
            uses: actions/cache@v4
            continue-on-error: false
            with:
              path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                ~/target/
              key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: ${{ runner.os }}-${{ github.job }}-
          - name: Build (default features)
            run: cargo build --workspace

    bench-compile:
        name: Run Compile Benchmarks
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
            - uses: dtolnay/rust-toolchain@stable
            - name: Set up Cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/target/
                key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-${{ github.job }}-
            - name: System Information
              run: lscpu
            - name: Compile (--profile ci)
              run: cargo build --benches --profile ci
            - name: Run Compilation Benches (--profile ci)
              run: cargo bench compile/ --profile ci

    bench-execute:
        name: Run Execution Benchmarks
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
            - uses: dtolnay/rust-toolchain@stable
            - name: Set up Cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/target/
                key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-${{ github.job }}-
            - name: System Information
              run: lscpu
            - name: Compile (--profile ci)
              run: cargo build --benches --profile ci
            - name: Run Execution Benches (--profile ci)
              run: cargo bench execute/ --profile ci

    coremark:
      name: Run Coremark
      needs: install-dependencies
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
          - uses: dtolnay/rust-toolchain@stable
          - name: Set up Cargo cache
            uses: actions/cache@v4
            continue-on-error: false
            with:
              path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                ~/target/
              key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: ${{ runner.os }}-${{ github.job }}-
          - name: System Information
            run: lscpu
          - name: Compile (--profile ci)
            run: cargo build --bin coremark --profile ci
          - name: Run Coremark (--profile ci)
            run: cargo run --bin coremark --profile ci

    fmt:
        name: Formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
            - uses: dtolnay/rust-toolchain@nightly
              with:
                components: rustfmt
            - name: Formatting
              run: cargo fmt --all -- --check

    doc:
        name: Documentation
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
            - uses: dtolnay/rust-toolchain@stable
              with:
                components: rust-docs, rust-src
            - name: Set up Cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/target/
                key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-${{ github.job }}-
            - name: Check Docs
              env:
                RUSTDOCFLAGS: "-D warnings"
              run: cargo doc --workspace --all-features --no-deps --document-private-items

    clippy:
        name: Clippy
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
            - uses: dtolnay/rust-toolchain@nightly
              with:
                components: clippy
            - name: Set up Cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/target/
                key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-${{ github.job }}-
            - name: Checkout Submodules
              run: git submodule update --init --recursive
            - name: Clippy (all features)
              run: cargo clippy --workspace --all-features -- -D warnings
